### ISSUE TITLE
Lowering dependencies 

### ISSUE THREAD

**Issue by slimshader** [FlatlinerDOA/Rope#7]
Hi,

What would be needed to lower .net requirements for this great library? Hoping to use it in Unity (.net standard 2.1)

**Comment by FlatlinerDOA** [comment]
Hi @slimshader it can be done but not without some performance hits. 
There were a quite a few places where .NET 8.0 features were required, check out PR  #8  for more information.

**Comment by slimshader** [comment]
So support for 2.1 is coming, fantastic news. Performance hit is expected. Thanks!
